name: solid_software_aplication
version: 1.0.0+1
description: A new Flutter project.

environment:
  sdk: ">=2.18.2 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  custom_navigation_bar: ^0.8.2
  flutter:
    sdk: flutter
  flutter_lints: ^2.0.0
  get: ^4.6.5
  solid_lints: ^0.0.15
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
